# Generated by Django 4.0.3 on 2022-08-25 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='food_items',
            field=models.ManyToManyField(blank=True, null=True, to='recipes.fooditem'),
        ),
    ]
